image: node:latest
stages:
  - pages
pages:
  cache:
    paths:
      - node_modules/
  stage: pages
  script:
    - npm install
    - npx parcel build -d public index.html
  artifacts:
    paths:
      - public
  only:
    - master
    
