image: node:latest
stages:
  - pages
pages:
  cache:
    paths:
      - node_modules/
  stage: pages
  script:
    - npm install
    - npx parcel build index.html
  artifacts:
    paths:
      - dist
    
