image: node:latest
stages:
  - test
  - pages

test:
  stage: test
  script:
    - npm install
    - npx elm-test

pages:
  stage: pages
  script:
    - npm install
    - npx parcel build -d public --public-url ./ index.html
  artifacts:
    paths:
      - public
  only:
    - master
